let bandeiraA = new Bandeira(111,'França', 'País da LadyBug e CatNoir🐞🐈‍⬛🇫🇷', 'França.jpeg', 'Há anos o país mais visitado do mundo, a França justifica sua preferência entre os turistas graças as mais variadas experiências que proporciona. A começar pela capital, Paris, onde história, cultura e muito romantismo conquistam qualquer visitante. Considere alugar um carro Paris e percorrer algumas das rotas mais belas da França, como o Vale do Loire e seus castelos, a Costa da Normandia e o surpreendente Mont Saint-Michel, os Campos de Lavanda e suas cores vibrantes nos meses de primavera – difícil vai ser escolher apenas uma!','torre.jpeg');

let bandeiraB = new Bandeira(112, 'Espanha', 'Xenofobia rola solta🇪🇦', 'Espanha.jpeg','A Espanha é um país imperdível para quem gosta de arte, cultura, gastronomia e festas – e costuma ser um dos países mais baratos para visitar na Europa. O desafio é montar um roteiro enxuto com tantos lugares diferentes para conhecer. Além das cosmopolitas Madri e Barcelona, vale também pesquisar sobre a charmosa região da Andaluzia. Mas se você prefere curtir as praias, procure saber mais sobre as ilhas Canárias ou Baleares… você vai entender porque as buscas pela Espanha cresceram nos últimos anos!','espanha2.jpeg');

let bandeiraC = new Bandeira(113, 'Estados Unidos', '"Democracy" HAHAHAHAHAH🇺🇲', 'USA.jpeg','Nova York, São Francisco, Miami, Orlando… talvez essas sejam cidades responsáveis por manter os Estados Unidos sempre entre os países mais visitados do mundo. Entre os viajantes brasileiros, o destino norte-americano mais desejado é Miami, possivelmente em função dos voos baratos e por ser um ótimo destino para compras. Não podemos deixar de notar o crescente interesse de viajantes internacionais por destinos de natureza, mesmo nos Estados Unidos. Com a pandemia, a busca por refúgios em meio à natureza aumentou, influenciando diretamente nas buscas por áreas mais tranquilas e pelos Parques Nacionais dos EUA.', 'usa2.jpeg');

let bandeiraD = new Bandeira(114, 'Turquia', 'a ponte entre a Europa e a Ásia🇹🇷', 'turquia.jpeg', 'A Turquia foi um dos destaques do relatório da OMT 2023: as receitas com turismo duplicaram esse ano em comparação com o primeiro trimestre de 2019. No país, tudo parece grandioso, da arquitetura antiga aos cenários naturais. E para ter uma ideia dessa magnitude, o ideal é conhecer de perto as atrações de Istambul e estender o roteiro a outros atrativos fora da capital. A Capadócia, no nosso imaginário desde que virou cenário da novela Salve Jorge, é um desses locais onde nos damos conta do nosso (diminuto) tamanho frente a grandiosidade da natureza. Já Pamukkale, um conjunto de piscinas naturais na região oeste do país, é praticamente um santuário natural buscado por fotógrafos do mundo inteiro.', 'turquia2.jpeg');

let bandeiraE = new Bandeira(115, 'Itália', 'O lugar da mãozinha do sal🇮🇹', 'italia.jpeg', 'Visitar a Itália é o sonho de muitos brasileiros. O país figura inclusive entre os destinos na Europa para fugir do inverno brasileiro – e põe fugir do frio nisso: as temperaturas na Itália podem passar dos 40ºC no verão europeu. A dica nessa época de altas temperaturas é conhecer o belo litoral italiano e provar muitos gelatos (sorvetes artesanais italianos) por lá. Agora, se você quer mesmo é sair passeando e se surpreender com prédios que remontam a época do Império Romano, com a arquitetura italiana e atrações mais turísticas, veja roteiros pela Itália que incluam cidades como Roma, Florença, Veneza e Milão.','italia2.jpeg');

let bandeiraF = new Bandeira(116, 'México', 'Dia de Los Muertos🇲🇽', 'mexico.jpeg', 'Para além da beleza tradicionalmente conhecida da Península de Yucatán, há inúmeras cidades do México para curtir toda a diversidade do país. A começar pela própria Cidade do México que é, ao mesmo tempo, o grande centro urbano e econômico do país e o coração pulsante de toda a cultura mexicana. A riqueza histórica e cultural, aliada à gastronomia singular e às belas paisagens, desperta a atenção dos viajantes mais curiosos em busca de destinos para ficar mais tempo. Frequentemente há passagens baratas para o México e os preços no país são mais econômicos que em outros destinos caribenhos, por exemplo.', 'mexico2.jpeg');

let bandeiraG = new Bandeira(117, 'Reino Unido', 'Rainha Elizabeth ainda está VIVA!🇬🇧', 'ReinoUnido.jpeg','As terras da coroa britânica impressionam… Inglaterra, País de Gales, Escócia e Irlanda do Norte, cada um com sua personalidade. O melhor é que juntos garantem um roteiro incrível pelo Reino Unido. Na Inglaterra, é inquestionável reservar vários dias para Londres, mas não se esqueça de lugares como Bath, Oxford e Liverpool (ainda mais se você é fã de Beatles). Na Escócia, descubra a cultura local e desbrave as Highlands, uma das regiões mais bonitas da Europa.', 'reinounido2.jpeg',);

let bandeiraH = new Bandeira(118, ' Alemanha', 'TE lascar com 7x1 vai!🇩🇪', 'alemanha.jpeg','Um país de castelos que inspiram contos de fadas e de cidades que guardam memórias de um dos mais marcantes conflitos mundiais. Viajar para a Alemanha é se deparar com contrastes entre o antigo e o novo, o rural e o urbano. Possivelmente é esse mix de lugares e experiências que trouxe a Alemanha para o radar dos viajantes nos últimos anos. Um bom roteiro pode combinar cidades como Berlim, capital do país e uma das cidades mais vibrantes de mundo, com Munique, lar da famosa Oktoberfest, e ainda um passeio pela doce Rota Romântica alemã.','alemanha2.jpeg');

let bandeiraI = new Bandeira(119, 'Grécia', 'Deuses Gregos🇬🇷', 'grecia.jpeg', 'A Grécia é um dos destinos dos sonhos dos brasileiros – e não é de hoje! Antes de figurar na lista dos países mais visitados do mundo, a Grécia já esteve muitas vezes nos top países mais buscados em nosso site. As ilhas gregas são as primeiras a despertar o desejo nos viajantes, mas o país pode oferecer muito mais do que casinhas brancas e praias de estonteantes tons de azul. A gastronomia mediterrânea é um show à parte, assim como a cultura e história gregas, especialmente na capital, Atenas.', 'grecia2.jpeg');

let bandeiraJ = new Bandeira(120, 'Áustria','tcha lapada que levou do Brasil ein kakakakaka🇦🇹', 'austria.jpeg', 'Berço de gênios da música erudita, como Mozart, Strauss e Schubert, a Áustria surpreende com o tanto de atrações em um território menor que o do estado de Santa Catarina, no Brasil. Montanhas nevadas, cidadezinhas impecáveis e paisagens bucólicas fazem parecer que estamos em um conto europeu. Um roteiro por aqui merece ter cidades como Viena, capital do país; Salzburgo, próxima à região dos lagos alpinos; e Innsbruck, um dos melhores lugares para ver neve e esquiar.','austria2.jpeg');



let paisesPopulares = []
paisesPopulares.push(bandeiraA, bandeiraB, bandeiraC, bandeiraD, bandeiraE, bandeiraF, bandeiraG, bandeiraH, bandeiraI, bandeiraJ);
